# Generated by Django 4.1.5 on 2024-08-11 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0002_customuser_full_name_customuser_mail_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$')]),
        ),
    ]
