# Generated by Django 4.1.5 on 2024-08-12 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0005_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adhar',
            field=models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
